---
- name: update facts
  setup:
  delegate_to: '{{item}}'
  delegate_facts: yes
  when: hostvars[item]["ansible_all_ipv4_addresses"] is not defined
  with_items: '{{groups["all"]}}'
  tags:
    - always

- name: install packages
  become: yes
  become_method: sudo
  yum: name={{item}} state=present
  with_items:
    - wget
    - unzip
    - vim

- name: "generate /etc/hosts.ansible file"
  become: yes
  become_method: sudo
  template:
    src: templates/hosts.j2
    dest: '/etc/hosts'
    owner: root
    group: root
    mode: 0644

- name: disable firewall
  become: yes
  become_method: sudo
  raw: "systemctl disable firewalld && systemctl stop firewalld"
