---
version: "1.3.3.6"
file: kafka-manager.zip
fileExtracted: kafka-manager-1.3.3.6
url: https://public.centerdevice.de/download/59cd252f-1058-4ce2-b915-5a239ff5ceb1.c2be1268-645e-0004-b83d-ee98ba1cfbcd