---
- name: Copy rpm file to server
  copy:
     src: files/python2-pip-8.1.2-8.el7.noarch.rpm 
     dest: /vagrant/download/python2-pip-8.1.2-8.el7.noarch.rpm

- name: Install package.
  yum:
     name: /vagrant/download/python2-pip-8.1.2-8.el7.noarch.rpm
     state: present

- pip:
    name: kafka-python

- name: copying solutuin 1
  become: yes
  become_method: sudo
  copy:
    src: files/producer-input.py
    dest: /usr/local/bin/producer-input.py
    mode: +x 

- name: copying solutuin 2
  become: yes
  become_method: sudo
  copy:
    src: files/producer-output.py
    dest: /usr/local/bin/producer-output.py
    mode: +x 

- name: install systemd services - 1
  become: yes
  become_method: sudo
  template:
    src: templates/producer-input.service.j2
    dest: "{{ system_units }}/producer-input.service"
  register: producer-input_service

- name: install systemd services - 2
  become: yes
  become_method: sudo
  template:
    src: templates/producer-output.service.j2
    dest: "{{ system_units }}/producer-output.service"
  register: producer-output_service

- name: restart solution 1
  become: yes
  become_method: sudo
  systemd:
    enabled: yes
    state: restarted
    name: producer-input.service

- name: restart solution 2
  become: yes
  become_method: sudo
  systemd:
    enabled: yes
    state: restarted
    name: producer-output.service
