---
- name: Create Apache Kafka input topic.
  shell: /home/vagrant/kafka/bin/kafka-topics.sh --zookeeper kafka-lab-1:2181 --replication-factor 1 --partitions 1 --topic input --create

- name: Create Apache Kafka output topic.
  shell: /home/vagrant/kafka/bin/kafka-topics.sh --zookeeper kafka-lab-1:2181 --replication-factor 1 --partitions 1 --topic output --create

- name: copying solutuin 1
  become: yes
  become_method: sudo
  copy:
    src: template/producer-input.sh
    dest: /usr/local/bin/producer-input.sh

- name: copying solutuin 2
  become: yes
  become_method: sudo
  copy:
    src: template/producer-output.sh
    dest: /usr/local/bin/producer-output.sh

- name: install systemd services - 1
  become: yes
  become_method: sudo
  template:
    src: templates/producer-input.service.j2
    dest: "{{ system_units }}/producer-input.service"
  register: producer-input_service

- name: install systemd services - 2
  become: yes
  become_method: sudo
  template:
    src: templates/producer-output.service.j2
    dest: "{{ system_units }}/producer-output.service"
  register: producer-output_service

- name: restart solution 1
  become: yes
  become_method: sudo
  systemd:
    enabled: yes
    state: restarted
    name: producer-input.service

- name: restart solution 2
  become: yes
  become_method: sudo
  systemd:
    enabled: yes
    state: restarted
    name: producer-output.service
