---

- name: push connect-standalone.properties
  template:
    src: templates/connect-standalone.properties.j2
    dest: "{{ kafka_home }}/config/connect-standalone.properties"
  tags:
    - kafka-connect-config

- name: download {{ mongodb_jar_url }}
  run_once: true
  get_url:
    url: "{{ mongodb_jar_url }}"
    dest: "{{ download }}/connect-mongodb-1.1.jar"
    mode: 0755

- name: copy connect-mongodb-1.1.jar to kafka libs folder
  copy:
    remote_src: True
    src: "{{ download }}/connect-mongodb-1.1.jar"
    dest: "{{ kafka_home }}/libs/connect-mongodb-1.1.jar"


