- hosts: all
  remote_user: vagrant
  serial: 100%
  roles:
    - common
    - java

- hosts: zookeeper
  remote_user: vagrant
  serial: 100%
  roles:
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  serial: 100%
  roles:
    - kafka

- hosts: solutions
  remote_user: vagrant
  serial: 100%
  roles:
    - solutions

- hosts: kafka-lab-3
  remote_user: vagrant
  serial: 100%
  roles:
    - { role: promeutheus, tags: ['promeutheus'] }

